"""Pitches Migration

Revision ID: 337d3878b785
Revises: 5757869ae0d8
Create Date: 2022-05-09 14:17:37.091871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337d3878b785'
down_revision = '5757869ae0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('the_pitch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitches')
    # ### end Alembic commands ###
