"""Migration

Revision ID: 437c2063ab55
Revises: 22f3e38ca323
Create Date: 2022-05-13 08:31:59.637855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437c2063ab55'
down_revision = '22f3e38ca323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
