"""Pitches Migration

Revision ID: 630c79c8bfe1
Revises: 65b596eebb72
Create Date: 2022-05-09 20:31:12.572808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630c79c8bfe1'
down_revision = '65b596eebb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.Text(), nullable=True))
    op.drop_column('pitches', 'the_pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('the_pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
